import { Providers } from "@/shared/providers";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const roboto = Roboto({
  weight: [
    "100", // Thin
    "300", // Light
    "400", // Regular
    "500", // Medium
    "700", // Bold
    "900", // Black
  ],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyClassName = twMerge(
  "max-w-screen min-h-screen antialiased text-foreground pt-3",
  roboto.className
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={bodyClassName}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
