name: Build Tauri App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-tauri:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js e PNPM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install PNPM
        run: npm install -g pnpm

      # Setup Rust, cargo e Tauri
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend (Next.js)
        run: pnpm build

      # Ajusta algumas dependências para cada plataforma, se necessário
      # Ex: no Linux pode ser necessário instalar pacotes extras.
      - name: Install platform-specific dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Caso seja necessário instalar toolchains
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev \
            libappindicator3-dev patchelf

      # Build Tauri
      # Você pode usar as diferentes scripts do package.json para cada SO se precisar.
      - name: Build Tauri
        run: pnpm tauri:build

      # Artefatos: subir o resultado do build
      # Ajuste o caminho conforme a localização do binário final (normalmente em `src-tauri/target/release/`)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*
