name: Build Tauri App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-tauri:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js e Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      # Instala dependências do projeto
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Se quiser cache de dependências do Rust (opcional)
      # - name: Cache cargo
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cargo
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cargo-

      # Setup Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Dependências específicas para Linux (se necessário)
      - name: Install platform-specific dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev patchelf

      # Build frontend (Next.js)
      - name: Build frontend
        run: yarn build

      # Build Tauri
      - name: Build Tauri
        run: yarn tauri:build

      # Upload dos artefatos (ajuste o caminho conforme a localização dos binários finais)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*
