name: Tauri Build and Release

on:
  push:
    tags:
      - "v*" # Aciona o workflow apenas para tags que começam com "v"

jobs:
  build:
    name: Build for All Platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust targets
        run: |
          rustup target add x86_64-pc-windows-gnu x86_64-unknown-linux-gnu aarch64-apple-darwin x86_64-apple-darwin

      - name: Install dependencies
        run: yarn install

      - name: Build for macOS ARM (Apple Silicon)
        if: matrix.os == 'macos-latest'
        run: yarn tauri:build:mac-arm

      - name: Build for macOS Intel
        if: matrix.os == 'macos-latest'
        run: yarn tauri:build:mac-intel

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn tauri:build:linux:deb

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: yarn tauri:build:win

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: src-tauri/target/release/bundle/
